#!/bin/bash
awk '
/id=\"um-print-sheet\"/ {
    print "              id=\"um-print-sheet\""
    print "              ref={printAreaRef}"
    print "              className=\"bg-slate-200/50 text-slate-900 p-6 rounded-2xl overflow-y-auto max-h-[600px] flex flex-wrap gap-4 shadow-inner justify-center items-center\""
    print "              style={{ direction: '"'"'rtl'"'"' }}"
    print "            >"
    print "              {previewBatchCards.map((card, idx) => {"
    print "                const activeTemplate = templates.find(t => t.id === batchTemplateId);"
    print "                if (activeTemplate) {"
    print "                  return ("
    print "                    <PrintableCard"
    print "                      key={idx}"
    print "                      template={activeTemplate}"
    print "                      networkName={settings.networkName || '"'"'شبكة الواي فاي'"'"'}"
    print "                      networkSlogan={settings.networkSlogan}"
    print "                      username={card.username}"
    print "                      password={card.pin}"
    print "                      profileName={card.profile}"
    print "                      serial={card.serial}"
    print "                      price={profiles.find(p => p.name === card.profile)?.price}"
    print "                      currency={settings.currencySymbol}"
    print "                      supportPhone={settings.supportPhone}"
    print "                    />"
    print "                  );"
    print "                }"
    print "                // Fallback rendering"
    print "                return ("
    print "                  <div"
    print "                    key={idx}"
    print "                    className=\"w-[85mm] h-[55mm] border-2 border-dashed border-slate-400 rounded-xl p-3 flex flex-col justify-between bg-white\""
    print "                  >"
    print "                    <div className=\"flex items-center justify-between border-b border-slate-200 pb-1.5 mb-1.5\">"
    print "                      <span className=\"font-black text-[12px] text-purple-900 truncate\">"
    print "                        {settings.networkName || '"'"'شبكة الواي فاي'"'"'}"
    print "                      </span>"
    print "                      <span className=\"text-[10px] font-bold px-2 py-0.5 rounded bg-purple-100 text-purple-800\">"
    print "                        {card.profile}"
    print "                      </span>"
    print "                    </div>"
    print "                    <div className=\"space-y-1.5 my-auto\">"
    print "                      <div className=\"bg-slate-50 p-2 rounded-lg border border-slate-200 text-center\">"
    print "                        <span className=\"text-[9px] text-slate-500 block\">اسم المستخدم</span>"
    print "                        <strong className=\"text-lg font-mono tracking-widest text-slate-900\">{card.username}</strong>"
    print "                      </div>"
    print "                      {card.username !== card.pin && ("
    print "                        <div className=\"bg-slate-50 p-2 rounded-lg border border-slate-200 text-center\">"
    print "                          <span className=\"text-[9px] text-slate-500 block\">كلمة المرور</span>"
    print "                          <strong className=\"text-lg font-mono tracking-widest text-slate-900\">{card.pin}</strong>"
    print "                        </div>"
    print "                      )}"
    print "                    </div>"
    print "                    <div className=\"flex items-center justify-between mt-1.5 border-t border-slate-200 pt-1.5\">"
    print "                      <span className=\"text-[9px] text-slate-400 font-mono\">SN: {card.serial}</span>"
    print "                      <span className=\"text-[9px] text-slate-500 font-bold bg-slate-100 px-1.5 py-0.5 rounded\">"
    print "                        {profiles.find(p => p.name === card.profile)?.price || 0} {settings.currencySymbol}"
    print "                      </span>"
    print "                    </div>"
    print "                  </div>"
    print "                );"
    print "              })}"
    in_block = 1
    next
}
in_block && /<\/div>/ {
    print "            </div>"
    in_block = 0
    next
}
in_block { next }
{ print }
' src/components/UserManagerView.tsx > temp.tsx && mv temp.tsx src/components/UserManagerView.tsx
