import {
  CardCategory,
  POSPoint,
  CardBatchDispatch,
  SalesRecord,
  PaymentRecord,
  NetworkSettings,
  GeneratedVoucher,
  CardTemplate,
  InvoiceRecord,
  ExpenseCategory,
  ExpenseRecord,
  AppUser,
  CardOrder,
  NetworkTenant,
} from './types';
import { getRoleDefaultPermissions } from './utils/permissions';

export const initialNetworkSettings: NetworkSettings = {
  networkName: "المنظومة السحابية لإدارة شبكات المايكروتك ونقاط البيع MicroSys",
  networkSlogan: "المنظومة السحابية المتكاملة للتحكم المالي، الفواتير، ونقاط البيع",
  currency: "YER",
  currencySymbol: "ر.ي",
  hotspotDns: "wifi.net",
  loginPageUrl: "http://wifi.net/login",
  supportPhone: "773703240",
  whatsappNumber: "967773703240",
  autoReconciliation: true,
  enableQrCodeOnCards: true,
  mikrotikIp: "192.168.88.1",
  mikrotikConfig: {
    host: "192.168.88.1",
    port: 8728,
    protocol: "auto",
    username: "admin",
    password: "",
    useSsl: false,
    autoRefreshInterval: 5,
    isLiveConnected: false,
    routerModel: "MikroTik RouterBOARD",
  },
  themeMode: "dark",
  invoiceFooterText: "تم استخراج هذا السند إلكترونياً عبر المنظومة السحابية لإدارة الشبكات ومبيعات الكروت • يرجى مراجعة الحسابات والاحتفاظ بالأصل",
  cashierFooterText: "شكراً لتعاملكم معنا • خدمة العملاء والدعم الفني: 773703240",
  statementFooterText: "كشف حساب رسمي معتمد صادر من النظام • يرجى مطابقة الأرصدة وإبداء أي ملاحظات خلال 3 أيام من تاريخه",
};

// Zeroed-out data collections across all networks
export const initialCategories: CardCategory[] = [];
export const initialPOSPoints: POSPoint[] = [];
export const initialCardOrders: CardOrder[] = [];
export const initialDispatches: CardBatchDispatch[] = [];
export const initialSales: SalesRecord[] = [];
export const initialPayments: PaymentRecord[] = [];
export const initialGeneratedVouchers: GeneratedVoucher[] = [];
export const initialInvoices: InvoiceRecord[] = [];
export const initialExpenses: ExpenseRecord[] = [];
export const initialTenants: NetworkTenant[] = [];

// Reusable Print Templates
export const initialTemplates: CardTemplate[] = [
  {
    id: "tpl-default-10",
    name: "قالب كروت قياسي ملون (A4 - 10 كروت)",
    description: "تصميم عصري متدرج الألوان مع باركود سريع QR ومعلومات الشبكة والفئة",
    backgroundType: "gradient",
    themeColor: "#6366f1",
    accentColor: "#ec4899",
    cardsPerPage: 10,
    gridCols: 2,
    gridRows: 5,
    orientation: "portrait",
    paperSize: "A4",
    showCutLines: true,
    cutLineStyle: "dashed",
    showQrCode: true,
    qrPosition: "right",
    qrSize: "md",
    qrHasWhiteBg: true,
    showNetworkName: true,
    showNetworkSlogan: true,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: false,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: false,
    codeBoxStyle: "rounded-white",
    codeTextColor: "#0f172a",
    codeFontSize: "md",
    codeLetterSpacing: "wide",
    createdAt: "2026-08-22",
  },
  {
    id: "tpl-light-30",
    name: "قالب كروت اقتصادي موفر للحبر (A4 - 30 كارت)",
    description: "خلفية بيضاء نقية موفرة للحبر تماماً، 30 كارت في الصفحة الواحدة لإنتاجية قصوى",
    backgroundType: "minimal_light",
    themeColor: "#475569",
    accentColor: "#1e293b",
    cardsPerPage: 30,
    gridCols: 3,
    gridRows: 10,
    orientation: "portrait",
    paperSize: "A4",
    showCutLines: true,
    cutLineStyle: "dashed",
    showQrCode: true,
    qrPosition: "left",
    qrSize: "sm",
    qrHasWhiteBg: false,
    showNetworkName: true,
    showNetworkSlogan: false,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: false,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: false,
    codeBoxStyle: "clean-border",
    codeTextColor: "#0f172a",
    codeFontSize: "md",
    codeLetterSpacing: "wide",
    createdAt: "2026-08-22",
  },
  {
    id: "tpl-thermal-pos",
    name: "قالب إيصالات الطباعة الحرارية (Thermal POS 80mm)",
    description: "مخصص لطابعات الفواتير والكاشير الحرارية مقاس 80mm و 58mm مع باركود سريع",
    backgroundType: "minimal_light",
    themeColor: "#0f172a",
    accentColor: "#334155",
    cardsPerPage: 1,
    gridCols: 1,
    gridRows: 1,
    orientation: "portrait",
    paperSize: "Thermal80mm",
    showCutLines: false,
    showQrCode: true,
    qrPosition: "center",
    qrSize: "lg",
    qrHasWhiteBg: true,
    showNetworkName: true,
    showNetworkSlogan: true,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: true,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: true,
    codeBoxStyle: "clean-border",
    codeTextColor: "#000000",
    codeFontSize: "xl",
    codeLetterSpacing: "widest",
    createdAt: "2026-08-23",
  }
];

// Presets for quick category creation by network managers
export const standardUserManagerPresets: Omit<CardCategory, 'id'>[] = [
  {
    name: "كارت 100 ريال (1 ساعة / 500 ميجا)",
    code: "100_1H",
    uptimeLimit: "1h",
    quotaLimit: "500M",
    rateLimit: "4M/2M",
    validityDays: 1,
    costPrice: 25,
    wholesalePrice: 80,
    retailPrice: 100,
    mikrotikProfile: "Profile-100",
    userManagerProfile: "UM-Profile-100",
    userManagerLimitation: "UM-Lim-100",
    sharedUsers: 1,
    warehouseStock: 0,
    colorTheme: "amber",
    notes: "فئة 100 ريال الاقتصادية للمارة والتصفح السريع",
  },
  {
    name: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
    code: "200_3H",
    uptimeLimit: "3h",
    quotaLimit: "1500M",
    rateLimit: "5M/2M",
    validityDays: 2,
    costPrice: 50,
    wholesalePrice: 160,
    retailPrice: 200,
    mikrotikProfile: "Profile-200",
    userManagerProfile: "UM-Profile-200",
    userManagerLimitation: "UM-Lim-200",
    sharedUsers: 1,
    warehouseStock: 0,
    colorTheme: "blue",
    notes: "فئة 200 ريال الأكثر مبيعاً",
  },
  {
    name: "كارت 500 ريال (يومي 24 ساعة / 3.5 جيجا)",
    code: "500_1D",
    uptimeLimit: "1d",
    quotaLimit: "3500M",
    rateLimit: "6M/3M",
    validityDays: 3,
    costPrice: 130,
    wholesalePrice: 420,
    retailPrice: 500,
    mikrotikProfile: "Profile-500",
    userManagerProfile: "UM-Profile-500",
    userManagerLimitation: "UM-Lim-500",
    sharedUsers: 1,
    warehouseStock: 0,
    colorTheme: "emerald",
    notes: "فئة 500 ريال اليومية",
  },
  {
    name: "كارت 1000 ريال (3 أيام / 8 جيجا)",
    code: "1000_3D",
    uptimeLimit: "3d",
    quotaLimit: "8G",
    rateLimit: "8M/4M",
    validityDays: 5,
    costPrice: 280,
    wholesalePrice: 850,
    retailPrice: 1000,
    mikrotikProfile: "Profile-1000",
    userManagerProfile: "UM-Profile-1000",
    userManagerLimitation: "UM-Lim-1000",
    sharedUsers: 1,
    warehouseStock: 0,
    colorTheme: "purple",
    notes: "فئة 1000 ريال - سرعة مضاعفة واستخدام متواصل",
  },
  {
    name: "كارت 1500 ريال (أسبوعي 7 أيام / 15 جيجا)",
    code: "1500_7D",
    uptimeLimit: "7d",
    quotaLimit: "15G",
    rateLimit: "8M/4M",
    validityDays: 7,
    costPrice: 420,
    wholesalePrice: 1250,
    retailPrice: 1500,
    mikrotikProfile: "Profile-1500",
    userManagerProfile: "UM-Profile-1500",
    userManagerLimitation: "UM-Lim-1500",
    sharedUsers: 1,
    warehouseStock: 0,
    colorTheme: "cyan",
    notes: "باقة الأسبوع الكامل",
  }
];

// Standard Expense Categories
export const initialExpenseCategories: ExpenseCategory[] = [
  {
    id: "exp-cat-1",
    name: "سعات وباقات الإنترنت الرئيسية (المزود)",
    description: "فواتير اشتراكات الإنترنت وخطوط الألياف والربط مع شركة الاتصالات / المزود الرئيسي",
    icon: "Wifi",
    colorTheme: "blue",
    isDefault: true,
  },
  {
    id: "exp-cat-2",
    name: "إيجارات الأبراج والمواقع",
    description: "إيجارات أسطح المنازل، الأبراج الرئيسية، ومواقع محطات البث",
    icon: "Radio",
    colorTheme: "purple",
    isDefault: true,
  },
  {
    id: "exp-cat-3",
    name: "الكهرباء والطاقة والمحروقات",
    description: "ديزل المولدات، فواتير الكهرباء، بطاريات ومنظومة الطاقة الشمسية",
    icon: "Zap",
    colorTheme: "amber",
    isDefault: true,
  },
  {
    id: "exp-cat-4",
    name: "الصيانة وقطع الغيار والتمديدات",
    description: "راوترات، كابلات شبكة، صحون ميكروتك، سويتشات، وصيانة ميدانية",
    icon: "Wrench",
    colorTheme: "emerald",
    isDefault: true,
  },
  {
    id: "exp-cat-5",
    name: "طباعة وتغليف وتوزيع الكروت",
    description: "مصاريف مطابع الكروت، الورق المقوى، التغليف الحراري، ونقل الدفعات",
    icon: "Printer",
    colorTheme: "rose",
    isDefault: true,
  },
  {
    id: "exp-cat-6",
    name: "رواتب ومكافآت الفنيين والموظفين",
    description: "رواتب مهندسي الشبكة، فنيي الصيانة، والمحصلين",
    icon: "Users",
    colorTheme: "indigo",
    isDefault: true,
  },
  {
    id: "exp-cat-7",
    name: "نثريات ومصاريف تشغيلية عامة",
    description: "مستلزمات مكتبية، اتصالات وضيافة، ومصروفات طارئة",
    icon: "Receipt",
    colorTheme: "slate",
    isDefault: true,
  },
];

// Only the Master User (System Owner) remains
export const initialUsers: AppUser[] = [
  {
    id: "user-system-owner",
    networkId: "system",
    name: "م. ماجد الورد (مالك النظام)",
    username: "master",
    password: "masterpassword",
    pinCode: "0000",
    role: "system_owner",
    customRoleName: "المالك لـ SaaS",
    avatar: "🏢",
    avatarBgColor: "bg-indigo-600",
    status: "active",
    permissions: getRoleDefaultPermissions("system_owner"),
    createdAt: "2026-01-01",
  },
];

export const mockTenants = initialTenants;
export const defaultNetworkSettings = initialNetworkSettings;
export const mockCategories = initialCategories;
export const mockPOSPoints = initialPOSPoints;
export const mockDispatches = initialDispatches;
export const mockSales = initialSales;
export const mockPayments = initialPayments;
export const mockGeneratedVouchers = initialGeneratedVouchers;
export const mockTemplates = initialTemplates;
export const mockExpenseCategories = initialExpenseCategories;
export const mockExpenses = initialExpenses;
export const mockInvoices = initialInvoices;
export const mockUsers = initialUsers;
export const mockCardOrders = initialCardOrders;
