import {
  CardCategory,
  POSPoint,
  CardBatchDispatch,
  SalesRecord,
  PaymentRecord,
  NetworkSettings,
  GeneratedVoucher,
  CardTemplate,
  InvoiceRecord,
  InvoiceItem,
  ExpenseCategory,
  ExpenseRecord,
  AppUser,
  CardOrder,
  CardOrderItem,
} from './types';
import { getRoleDefaultPermissions } from './utils/permissions';

export const initialNetworkSettings: NetworkSettings = {
  networkName: "شبكة الفضاء اللاسلكية | Al-Fadaa WiFi",
  networkSlogan: "سرعة فائقة وتغطية شاملة 24/7",
  currency: "YER",
  currencySymbol: "ر.ي",
  hotspotDns: "wifi.net",
  loginPageUrl: "http://wifi.net/login",
  supportPhone: "770123456",
  whatsappNumber: "967770123456",
  autoReconciliation: true,
  enableQrCodeOnCards: true,
  mikrotikIp: "192.168.88.1",
  mikrotikConfig: {
    host: "192.168.88.1",
    port: 8728,
    protocol: "auto",
    username: "admin",
    password: "",
    useSsl: false,
    autoRefreshInterval: 5,
    isLiveConnected: false,
    routerModel: "MikroTik RouterBOARD",
  },
  themeMode: "dark",
};

export const initialCategories: CardCategory[] = [
  {
    id: "cat-1",
    name: "كارت 100 ريال (1 ساعة / 500 ميجا)",
    code: "100_1H",
    uptimeLimit: "1h",
    quotaLimit: "500M",
    rateLimit: "4M/2M",
    validityDays: 1,
    costPrice: 25,
    wholesalePrice: 80,
    retailPrice: 100,
    mikrotikProfile: "Profile-100",
    userManagerProfile: "UM-Profile-100",
    userManagerLimitation: "UM-Lim-100",
    sharedUsers: 1,
    warehouseStock: 500,
    colorTheme: "amber",
    notes: "فئة 100 ريال الاقتصادية للمارة والتصفح السريع",
  },
  {
    id: "cat-2",
    name: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
    code: "200_3H",
    uptimeLimit: "3h",
    quotaLimit: "1500M",
    rateLimit: "5M/2M",
    validityDays: 2,
    costPrice: 50,
    wholesalePrice: 160,
    retailPrice: 200,
    mikrotikProfile: "Profile-200",
    userManagerProfile: "UM-Profile-200",
    userManagerLimitation: "UM-Lim-200",
    sharedUsers: 1,
    warehouseStock: 420,
    colorTheme: "blue",
    notes: "فئة 200 ريال الأكثر مبيعاً في الكافيهات والمحلات",
  },
  {
    id: "cat-3",
    name: "كارت 500 ريال (يومي 24 ساعة / 3.5 جيجا)",
    code: "500_1D",
    uptimeLimit: "1d",
    quotaLimit: "3500M",
    rateLimit: "6M/3M",
    validityDays: 3,
    costPrice: 130,
    wholesalePrice: 420,
    retailPrice: 500,
    mikrotikProfile: "Profile-500",
    userManagerProfile: "UM-Profile-500",
    userManagerLimitation: "UM-Lim-500",
    sharedUsers: 1,
    warehouseStock: 350,
    colorTheme: "emerald",
    notes: "فئة 500 ريال اليومية مناسبة للطلاب وأصحاب الأعمال",
  },
  {
    id: "cat-4",
    name: "كارت 1000 ريال (3 أيام / 8 جيجا)",
    code: "1000_3D",
    uptimeLimit: "3d",
    quotaLimit: "8G",
    rateLimit: "8M/4M",
    validityDays: 5,
    costPrice: 280,
    wholesalePrice: 850,
    retailPrice: 1000,
    mikrotikProfile: "Profile-1000",
    userManagerProfile: "UM-Profile-1000",
    userManagerLimitation: "UM-Lim-1000",
    sharedUsers: 1,
    warehouseStock: 250,
    colorTheme: "purple",
    notes: "فئة 1000 ريال - سرعة مضاعفة واستخدام متواصل",
  },
  {
    id: "cat-5",
    name: "كارت 1500 ريال (أسبوعي 7 أيام / 15 جيجا)",
    code: "1500_7D",
    uptimeLimit: "7d",
    quotaLimit: "15G",
    rateLimit: "8M/4M",
    validityDays: 7,
    costPrice: 420,
    wholesalePrice: 1250,
    retailPrice: 1500,
    mikrotikProfile: "Profile-1500",
    userManagerProfile: "UM-Profile-1500",
    userManagerLimitation: "UM-Lim-1500",
    sharedUsers: 1,
    warehouseStock: 180,
    colorTheme: "cyan",
    notes: "باقة الأسبوع الكامل - حجم عالي وتغطية ممتازة",
  },
  {
    id: "cat-6",
    name: "كارت 5000 ريال (شهري 30 يوم VIP / 60 جيجا)",
    code: "5000_30D",
    uptimeLimit: "30d",
    quotaLimit: "60G",
    rateLimit: "12M/6M",
    validityDays: 30,
    costPrice: 1200,
    wholesalePrice: 4200,
    retailPrice: 5000,
    mikrotikProfile: "Profile-5000",
    userManagerProfile: "UM-Profile-5000",
    userManagerLimitation: "UM-Lim-5000",
    sharedUsers: 2,
    warehouseStock: 80,
    colorTheme: "rose",
    notes: "باقة VIP الشهرية بدون تقطيع للألعاب والفيديو والبث المباشر",
  },
];

export const standardUserManagerPresets: Omit<CardCategory, 'id'>[] = [
  {
    name: "كارت 100 ريال (1 ساعة / 500 ميجا)",
    code: "100_1H",
    uptimeLimit: "1h",
    quotaLimit: "500M",
    rateLimit: "4M/2M",
    validityDays: 1,
    costPrice: 25,
    wholesalePrice: 80,
    retailPrice: 100,
    mikrotikProfile: "Profile-100",
    userManagerProfile: "UM-Profile-100",
    userManagerLimitation: "UM-Lim-100",
    sharedUsers: 1,
    warehouseStock: 300,
    colorTheme: "amber",
    notes: "فئة 100 ريال",
  },
  {
    name: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
    code: "200_3H",
    uptimeLimit: "3h",
    quotaLimit: "1500M",
    rateLimit: "5M/2M",
    validityDays: 2,
    costPrice: 50,
    wholesalePrice: 160,
    retailPrice: 200,
    mikrotikProfile: "Profile-200",
    userManagerProfile: "UM-Profile-200",
    userManagerLimitation: "UM-Lim-200",
    sharedUsers: 1,
    warehouseStock: 300,
    colorTheme: "blue",
    notes: "فئة 200 ريال",
  },
  {
    name: "كارت 300 ريال (5 ساعات / 2.5 جيجا)",
    code: "300_5H",
    uptimeLimit: "5h",
    quotaLimit: "2500M",
    rateLimit: "5M/2M",
    validityDays: 2,
    costPrice: 80,
    wholesalePrice: 240,
    retailPrice: 300,
    mikrotikProfile: "Profile-300",
    userManagerProfile: "UM-Profile-300",
    userManagerLimitation: "UM-Lim-300",
    sharedUsers: 1,
    warehouseStock: 200,
    colorTheme: "teal",
    notes: "فئة 300 ريال",
  },
  {
    name: "كارت 500 ريال (يومي 24 ساعة / 3.5 جيجا)",
    code: "500_1D",
    uptimeLimit: "1d",
    quotaLimit: "3500M",
    rateLimit: "6M/3M",
    validityDays: 3,
    costPrice: 130,
    wholesalePrice: 420,
    retailPrice: 500,
    mikrotikProfile: "Profile-500",
    userManagerProfile: "UM-Profile-500",
    userManagerLimitation: "UM-Lim-500",
    sharedUsers: 1,
    warehouseStock: 250,
    colorTheme: "emerald",
    notes: "فئة 500 ريال اليومية",
  },
  {
    name: "كارت 1000 ريال (3 أيام / 8 جيجا)",
    code: "1000_3D",
    uptimeLimit: "3d",
    quotaLimit: "8G",
    rateLimit: "8M/4M",
    validityDays: 5,
    costPrice: 280,
    wholesalePrice: 850,
    retailPrice: 1000,
    mikrotikProfile: "Profile-1000",
    userManagerProfile: "UM-Profile-1000",
    userManagerLimitation: "UM-Lim-1000",
    sharedUsers: 1,
    warehouseStock: 200,
    colorTheme: "purple",
    notes: "فئة 1000 ريال",
  },
  {
    name: "كارت 1500 ريال (أسبوعي 7 أيام / 15 جيجا)",
    code: "1500_7D",
    uptimeLimit: "7d",
    quotaLimit: "15G",
    rateLimit: "8M/4M",
    validityDays: 7,
    costPrice: 420,
    wholesalePrice: 1250,
    retailPrice: 1500,
    mikrotikProfile: "Profile-1500",
    userManagerProfile: "UM-Profile-1500",
    userManagerLimitation: "UM-Lim-1500",
    sharedUsers: 1,
    warehouseStock: 150,
    colorTheme: "cyan",
    notes: "فئة 1500 ريال أسبوعي",
  },
  {
    name: "كارت 3000 ريال (نصف شهري 15 يوم / 30 جيجا)",
    code: "3000_15D",
    uptimeLimit: "15d",
    quotaLimit: "30G",
    rateLimit: "10M/5M",
    validityDays: 15,
    costPrice: 800,
    wholesalePrice: 2500,
    retailPrice: 3000,
    mikrotikProfile: "Profile-3000",
    userManagerProfile: "UM-Profile-3000",
    userManagerLimitation: "UM-Lim-3000",
    sharedUsers: 2,
    warehouseStock: 100,
    colorTheme: "indigo",
    notes: "فئة 3000 ريال",
  },
  {
    name: "كارت 5000 ريال (شهري 30 يوم VIP / 60 جيجا)",
    code: "5000_30D",
    uptimeLimit: "30d",
    quotaLimit: "60G",
    rateLimit: "12M/6M",
    validityDays: 30,
    costPrice: 1200,
    wholesalePrice: 4200,
    retailPrice: 5000,
    mikrotikProfile: "Profile-5000",
    userManagerProfile: "UM-Profile-5000",
    userManagerLimitation: "UM-Lim-5000",
    sharedUsers: 2,
    warehouseStock: 80,
    colorTheme: "rose",
    notes: "فئة 5000 ريال VIP شهري",
  },
];

export const initialPOSPoints: POSPoint[] = [
  {
    id: "pos-1",
    name: "بقالة الأمانة والسلام",
    managerName: "أبو أحمد الشامي",
    phone: "771234567",
    address: "شارع الستين - جوار مدرسة النجاح",
    maxDebtLimit: 50000,
    currentDebt: 8600,
    totalCardsDelivered: 170,
    totalCardsSold: 160,
    totalCashPaid: 15000,
    status: "active",
    pinCode: "1111",
    username: "pos_amana",
    password: "pospassword1",
    notes: "موزع رئيسي ملتزم بالسداد كل يوم اثنين",
    createdAt: "2026-01-10",
  },
  {
    id: "pos-2",
    name: "كافيه ديوان القمة",
    managerName: "محمد اليعري",
    phone: "772345678",
    address: "حي الجامعة - شارع المطاعم",
    maxDebtLimit: 80000,
    currentDebt: 29900,
    totalCardsDelivered: 205,
    totalCardsSold: 205,
    totalCashPaid: 25000,
    status: "active",
    pinCode: "2222",
    username: "pos_diwan",
    password: "pospassword2",
    notes: "مبيعات عالية جداً لكروت الـ 3 ساعات واليومي",
    createdAt: "2026-01-15",
  },
  {
    id: "pos-3",
    name: "سوبرماركت النخيل الحديث",
    managerName: "خالد بن عمر",
    phone: "773456789",
    address: "تقاطع حي الأندلس",
    maxDebtLimit: 60000,
    currentDebt: 0,
    totalCardsDelivered: 60,
    totalCardsSold: 0,
    totalCashPaid: 0,
    status: "active",
    pinCode: "3333",
    username: "pos_nakheel",
    password: "pospassword3",
    notes: "يسدد نقداً عند طلب الدفعات الجديدة",
    createdAt: "2026-02-01",
  },
  {
    id: "pos-4",
    name: "كشك شباب المستقبل",
    managerName: "علي باسويد",
    phone: "774567890",
    address: "موقف الباصات الرئيسي",
    maxDebtLimit: 25000,
    currentDebt: 0,
    totalCardsDelivered: 0,
    totalCardsSold: 0,
    totalCashPaid: 8000,
    status: "active",
    pinCode: "4444",
    username: "pos_shabab",
    password: "pospassword4",
    notes: "طلب أكثر على كروت الساعة والـ 3 ساعات",
    createdAt: "2026-02-12",
  },
  {
    id: "pos-5",
    name: "محل إكسبريس للاتصالات",
    managerName: "طارق منصور",
    phone: "775678901",
    address: "السوق التجاري المركزي",
    maxDebtLimit: 100000,
    currentDebt: 42500,
    totalCardsDelivered: 60,
    totalCardsSold: 60,
    totalCashPaid: 50000,
    status: "active",
    pinCode: "5555",
    username: "pos_express",
    password: "pospassword5",
    notes: "يبيع جميع الفئات ولديه حركة ممتازة للكروت الشهرية",
    createdAt: "2026-01-05",
  },
  {
    id: "pos-6",
    name: "صيدلية الدواء الشافي",
    managerName: "د. سامي العولقي",
    phone: "776789012",
    address: "الشارع العام - مقابل المستوصف",
    maxDebtLimit: 20000,
    currentDebt: 0,
    totalCardsDelivered: 0,
    totalCardsSold: 0,
    totalCashPaid: 0,
    status: "active",
    pinCode: "6666",
    username: "pos_dawa",
    password: "pospassword6",
    notes: "نقطة توزيع إضافية هادئة",
    createdAt: "2026-02-20",
  },
];

export const initialCardOrders: CardOrder[] = [
  {
    id: "ord-101",
    orderNumber: "ORD-2026-001",
    posPointId: "pos-1",
    posPointName: "بقالة الأمانة والسلام",
    posPhone: "771234567",
    posAddress: "شارع الستين - جوار مدرسة النجاح",
    items: [
      {
        categoryId: "cat-1",
        categoryName: "كارت 100 ريال (1 ساعة / 500 ميجا)",
        quantity: 50,
        unitWholesalePrice: 80,
        totalWholesalePrice: 4000,
        unitRetailPrice: 100,
        totalRetailPrice: 5000,
      },
      {
        categoryId: "cat-2",
        categoryName: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
        quantity: 30,
        unitWholesalePrice: 160,
        totalWholesalePrice: 4800,
        unitRetailPrice: 200,
        totalRetailPrice: 6000,
      },
    ],
    totalQuantity: 80,
    totalWholesaleAmount: 8800,
    totalRetailAmount: 11000,
    currentDebtAtRequest: 8600,
    status: "pending",
    priority: "urgent",
    requestDate: "2026-08-28",
    timestamp: "2026-08-28T09:15:00Z",
    notes: "يرجى الإرسال عاجلاً، كروت فئة 100 أوشكت على النفاد تماماً.",
  },
  {
    id: "ord-102",
    orderNumber: "ORD-2026-002",
    posPointId: "pos-2",
    posPointName: "كافيه ديوان القمة",
    posPhone: "772345678",
    posAddress: "حي الجامعة - شارع المطاعم",
    items: [
      {
        categoryId: "cat-2",
        categoryName: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
        quantity: 100,
        unitWholesalePrice: 160,
        totalWholesalePrice: 16000,
        unitRetailPrice: 200,
        totalRetailPrice: 20000,
      },
      {
        categoryId: "cat-3",
        categoryName: "كارت 500 ريال (يومي 24 ساعة / 3.5 جيجا)",
        quantity: 20,
        unitWholesalePrice: 420,
        totalWholesalePrice: 8400,
        unitRetailPrice: 500,
        totalRetailPrice: 10000,
      },
    ],
    totalQuantity: 120,
    totalWholesaleAmount: 24400,
    totalRetailAmount: 30000,
    currentDebtAtRequest: 29900,
    status: "processing",
    priority: "normal",
    requestDate: "2026-08-27",
    timestamp: "2026-08-27T16:40:00Z",
    notes: "دفعة نهاية الأسبوع للكافيه",
    adminNotes: "جاري الطباعة والتجهيز وسيسلمها المندوب سالم عصراً.",
  },
  {
    id: "ord-103",
    orderNumber: "ORD-2026-003",
    posPointId: "pos-3",
    posPointName: "سوبرماركت النخيل الحديث",
    posPhone: "773456789",
    posAddress: "تقاطع حي الأندلس",
    items: [
      {
        categoryId: "cat-4",
        categoryName: "كارت 1000 ريال (3 أيام / 8 جيجا)",
        quantity: 15,
        unitWholesalePrice: 850,
        totalWholesalePrice: 12750,
        unitRetailPrice: 1000,
        totalRetailPrice: 15000,
      },
    ],
    totalQuantity: 15,
    totalWholesaleAmount: 12750,
    totalRetailAmount: 15000,
    currentDebtAtRequest: 0,
    status: "delivered",
    priority: "normal",
    requestDate: "2026-08-26",
    timestamp: "2026-08-26T11:00:00Z",
    notes: "سنسدد نقداً عند وصول المندوب",
    adminNotes: "تم التسليم بنجاح وإصدار الفاتورة.",
    convertedInvoiceId: "INV-2026-003",
  },
];

export const initialDispatches: CardBatchDispatch[] = [
  {
    id: "disp-101",
    date: "2026-08-15",
    posPointId: "pos-1",
    categoryId: "cat-1",
    quantity: 100,
    unitWholesalePrice: 120,
    totalWholesaleValue: 12000,
    unitRetailPrice: 150,
    totalRetailValue: 15000,
    serialStart: "10001",
    serialEnd: "10100",
    status: "partially_sold",
    soldCount: 85,
    notes: "دفعة كروت 1 ساعة لبقالة الأمانة",
  },
  {
    id: "disp-102",
    date: "2026-08-16",
    posPointId: "pos-1",
    categoryId: "cat-2",
    quantity: 50,
    unitWholesalePrice: 240,
    totalWholesaleValue: 12000,
    unitRetailPrice: 300,
    totalRetailValue: 15000,
    serialStart: "20001",
    serialEnd: "20050",
    status: "partially_sold",
    soldCount: 40,
    notes: "دفعة 3 ساعات",
  },
  {
    id: "disp-103",
    date: "2026-08-17",
    posPointId: "pos-2",
    categoryId: "cat-2",
    quantity: 150,
    unitWholesalePrice: 240,
    totalWholesaleValue: 36000,
    unitRetailPrice: 300,
    totalRetailValue: 45000,
    serialStart: "20101",
    serialEnd: "20250",
    status: "partially_sold",
    soldCount: 130,
    notes: "دفعة كافيه ديوان القمة المعتادة",
  },
  {
    id: "disp-104",
    date: "2026-08-18",
    posPointId: "pos-2",
    categoryId: "cat-3",
    quantity: 80,
    unitWholesalePrice: 420,
    totalWholesaleValue: 33600,
    unitRetailPrice: 500,
    totalRetailValue: 40000,
    serialStart: "30001",
    serialEnd: "30080",
    status: "partially_sold",
    soldCount: 65,
    notes: "دفعة يومي 2.5G",
  },
  {
    id: "disp-105",
    date: "2026-08-19",
    posPointId: "pos-3",
    categoryId: "cat-3",
    quantity: 60,
    unitWholesalePrice: 420,
    totalWholesaleValue: 25200,
    unitRetailPrice: 500,
    totalRetailValue: 30000,
    serialStart: "30101",
    serialEnd: "30160",
    status: "partially_sold",
    soldCount: 45,
    notes: "دفعة يومي لسوبرماركت النخيل",
  },
  {
    id: "disp-106",
    date: "2026-08-20",
    posPointId: "pos-5",
    categoryId: "cat-4",
    quantity: 30,
    unitWholesalePrice: 1250,
    totalWholesaleValue: 37500,
    unitRetailPrice: 1500,
    totalRetailValue: 45000,
    serialStart: "40001",
    serialEnd: "40030",
    status: "partially_sold",
    soldCount: 22,
    notes: "دفعة أسبوعي لإكسبريس للاتصالات",
  },
  {
    id: "disp-107",
    date: "2026-08-21",
    posPointId: "pos-5",
    categoryId: "cat-5",
    quantity: 15,
    unitWholesalePrice: 4200,
    totalWholesaleValue: 63000,
    unitRetailPrice: 5000,
    totalRetailValue: 75000,
    serialStart: "50001",
    serialEnd: "50015",
    status: "partially_sold",
    soldCount: 9,
    notes: "دفعة VIP شهرية",
  },
  {
    id: "disp-108",
    date: "2026-08-22",
    posPointId: "pos-4",
    categoryId: "cat-1",
    quantity: 80,
    unitWholesalePrice: 120,
    totalWholesaleValue: 9600,
    unitRetailPrice: 150,
    totalRetailValue: 12000,
    serialStart: "10151",
    serialEnd: "10230",
    status: "partially_sold",
    soldCount: 50,
    notes: "دفعة كشك موقف الباصات",
  },
];

export const initialSales: SalesRecord[] = [
  {
    id: "sale-501",
    date: "2026-08-20",
    timestamp: "2026-08-20T10:15:00Z",
    posPointId: "pos-1",
    categoryId: "cat-1",
    quantity: 30,
    unitRetailPrice: 150,
    totalRetailAmount: 4500,
    unitWholesalePrice: 120,
    totalWholesaleAmount: 3600,
    profit: 2100,
    paymentType: "credit",
    invoiceNumber: "INV-2026-001",
    notes: "مبيعات صباحية",
  },
  {
    id: "sale-502",
    date: "2026-08-20",
    timestamp: "2026-08-20T14:30:00Z",
    posPointId: "pos-2",
    categoryId: "cat-2",
    quantity: 45,
    unitRetailPrice: 300,
    totalRetailAmount: 13500,
    unitWholesalePrice: 240,
    totalWholesaleAmount: 10800,
    profit: 6300,
    paymentType: "credit",
    invoiceNumber: "INV-2026-002",
    notes: "مبيعات فترة الظهيرة بالكافيه",
  },
  {
    id: "sale-503",
    date: "2026-08-21",
    timestamp: "2026-08-21T09:00:00Z",
    posPointId: "pos-3",
    categoryId: "cat-3",
    quantity: 20,
    unitRetailPrice: 500,
    totalRetailAmount: 10000,
    unitWholesalePrice: 420,
    totalWholesaleAmount: 8400,
    profit: 4800,
    paymentType: "cash",
    invoiceNumber: "INV-2026-003",
    notes: "سددت نقداً عند التسليم",
  },
  {
    id: "sale-504",
    date: "2026-08-21",
    timestamp: "2026-08-21T18:20:00Z",
    posPointId: "pos-5",
    categoryId: "cat-4",
    quantity: 12,
    unitRetailPrice: 1500,
    totalRetailAmount: 18000,
    unitWholesalePrice: 1250,
    totalWholesaleAmount: 15000,
    profit: 9600,
    paymentType: "credit",
    invoiceNumber: "INV-2026-004",
    notes: "مبيعات نهاية الأسبوع",
  },
  {
    id: "sale-505",
    date: "2026-08-22",
    timestamp: "2026-08-22T11:45:00Z",
    posPointId: "pos-2",
    categoryId: "cat-2",
    quantity: 35,
    unitRetailPrice: 300,
    totalRetailAmount: 10500,
    unitWholesalePrice: 240,
    totalWholesaleAmount: 8400,
    profit: 4900,
    paymentType: "credit",
    invoiceNumber: "INV-2026-005",
  },
  {
    id: "sale-506",
    date: "2026-08-22",
    timestamp: "2026-08-22T16:00:00Z",
    posPointId: "pos-4",
    categoryId: "cat-1",
    quantity: 25,
    unitRetailPrice: 150,
    totalRetailAmount: 3750,
    unitWholesalePrice: 120,
    totalWholesaleAmount: 3000,
    profit: 1750,
    paymentType: "credit",
    invoiceNumber: "INV-2026-006",
  },
  {
    id: "sale-507",
    date: "2026-08-23",
    timestamp: "2026-08-23T10:00:00Z",
    posPointId: "pos-5",
    categoryId: "cat-5",
    quantity: 4,
    unitRetailPrice: 5000,
    totalRetailAmount: 20000,
    unitWholesalePrice: 4200,
    totalWholesaleAmount: 16800,
    profit: 12000,
    paymentType: "credit",
    invoiceNumber: "INV-2026-007",
    notes: "اشتراكات كروت VIP شهرية",
  },
  {
    id: "sale-508",
    date: "2026-08-23",
    timestamp: "2026-08-23T14:10:00Z",
    posPointId: "pos-1",
    categoryId: "cat-2",
    quantity: 15,
    unitRetailPrice: 300,
    totalRetailAmount: 4500,
    unitWholesalePrice: 240,
    totalWholesaleAmount: 3600,
    profit: 2100,
    paymentType: "credit",
    invoiceNumber: "INV-2026-008",
  },
  {
    id: "sale-509",
    date: "2026-08-23",
    timestamp: "2026-08-23T17:30:00Z",
    posPointId: "pos-2",
    categoryId: "cat-3",
    quantity: 25,
    unitRetailPrice: 500,
    totalRetailAmount: 12500,
    unitWholesalePrice: 420,
    totalWholesaleAmount: 10500,
    profit: 6000,
    paymentType: "credit",
    invoiceNumber: "INV-2026-009",
  },
];

export const initialPayments: PaymentRecord[] = [
  {
    id: "pay-301",
    date: "2026-08-18",
    timestamp: "2026-08-18T12:00:00Z",
    posPointId: "pos-1",
    amount: 15000,
    paymentMethod: "cash",
    receivedBy: "المدير المالي",
    notes: "دفعة نقدية تحت الحساب",
  },
  {
    id: "pay-302",
    date: "2026-08-19",
    timestamp: "2026-08-19T17:30:00Z",
    posPointId: "pos-2",
    amount: 25000,
    paymentMethod: "cash",
    receivedBy: "محصل الشبكة",
    notes: "سداد مبيعات بداية الأسبوع",
  },
  {
    id: "pay-303",
    date: "2026-08-21",
    timestamp: "2026-08-21T11:00:00Z",
    posPointId: "pos-5",
    amount: 50000,
    paymentMethod: "bank_transfer",
    referenceNumber: "TRX-998822",
    receivedBy: "حوالة كريمي",
    notes: "تسديد كروت شهرية وأسبوعية",
  },
  {
    id: "pay-304",
    date: "2026-08-22",
    timestamp: "2026-08-22T19:00:00Z",
    posPointId: "pos-4",
    amount: 8000,
    paymentMethod: "cash",
    receivedBy: "محصل الشبكة",
    notes: "دفعة من حساب كشك الباصات",
  },
];

export const initialGeneratedVouchers: GeneratedVoucher[] = [
  {
    id: "vouch-1",
    username: "849201",
    password: "849",
    categoryId: "cat-1",
    categoryName: "كارت 1 ساعة (سريع)",
    profile: "Profile-1Hour",
    price: 150,
    serial: "10001",
    batchCode: "B-202608-01",
    createdAt: "2026-08-20",
    status: "available",
  },
  {
    id: "vouch-2",
    username: "849202",
    password: "850",
    categoryId: "cat-1",
    categoryName: "كارت 1 ساعة (سريع)",
    profile: "Profile-1Hour",
    price: 150,
    serial: "10002",
    batchCode: "B-202608-01",
    createdAt: "2026-08-20",
    status: "available",
  },
  {
    id: "vouch-3",
    username: "731940",
    password: "731",
    categoryId: "cat-2",
    categoryName: "كارت 3 ساعات (1 جيجا)",
    profile: "Profile-3Hours",
    price: 300,
    serial: "20001",
    batchCode: "B-202608-02",
    createdAt: "2026-08-21",
    status: "available",
  },
  {
    id: "vouch-4",
    username: "618492",
    password: "618",
    categoryId: "cat-3",
    categoryName: "كارت يومي 24 ساعة (2.5 جيجا)",
    profile: "Profile-1Day",
    price: 500,
    serial: "30001",
    batchCode: "B-202608-03",
    createdAt: "2026-08-22",
    status: "available",
  },
];

export const initialTemplates: CardTemplate[] = [
  {
    id: "tpl-gold-18",
    name: "قالب باقة 500 ريال الذهبي الملكي (A4 - 18 كارت)",
    description: "تصميم ذهبي ملكي فخم مع باركود QR وخانات واضحة ومثالي لورقة A4 (3 أعمدة × 6 صفوف)",
    categoryId: "cat-3",
    backgroundType: "golden_luxury",
    themeColor: "#f59e0b",
    accentColor: "#78350f",
    cardsPerPage: 18,
    gridCols: 3,
    gridRows: 6,
    orientation: "portrait",
    paperSize: "A4",
    showCutLines: true,
    cutLineStyle: "dashed",
    showQrCode: true,
    qrPosition: "left",
    qrSize: "md",
    qrHasWhiteBg: true,
    showNetworkName: true,
    showNetworkSlogan: true,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: true,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: true,
    showFooterBanner: true,
    codeBoxStyle: "rounded-white",
    codeTextColor: "#0f172a",
    codeFontSize: "lg",
    codeLetterSpacing: "wide",
    createdAt: "2026-08-20",
    isDefault: true,
  },
  {
    id: "tpl-vip-10",
    name: "قالب باقة VIP 1000 ريال الفضائي (A4 - 10 كروت عريضة)",
    description: "تصميم عريض وفخم جداً عالي الوضوح، ممتاز للكروت الشهرية وكروت الـ VIP (عمودين × 5 صفوف)",
    categoryId: "cat-4",
    backgroundType: "dark_neon",
    themeColor: "#8b5cf6",
    accentColor: "#3b82f6",
    cardsPerPage: 10,
    gridCols: 2,
    gridRows: 5,
    orientation: "portrait",
    paperSize: "A4",
    showCutLines: true,
    cutLineStyle: "solid",
    showQrCode: true,
    qrPosition: "left",
    qrSize: "lg",
    qrHasWhiteBg: true,
    showNetworkName: true,
    showNetworkSlogan: true,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: true,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: true,
    showFooterBanner: true,
    codeBoxStyle: "amber-box",
    codeTextColor: "#0f172a",
    codeFontSize: "xl",
    codeLetterSpacing: "widest",
    createdAt: "2026-08-21",
  },
  {
    id: "tpl-blue-24",
    name: "قالب كروت 200 ريال الأزرق التكنولوجي (A4 - 24 كارت)",
    description: "تصميم عصري جذاب بكثافة طباعة عالية (4 أعمدة × 6 صفوف) لتوفير الورق مع الحفاظ على وضوح الرموز",
    categoryId: "cat-2",
    backgroundType: "cyan_tech",
    themeColor: "#0284c7",
    accentColor: "#0369a1",
    cardsPerPage: 24,
    gridCols: 4,
    gridRows: 6,
    orientation: "portrait",
    paperSize: "A4",
    showCutLines: true,
    cutLineStyle: "dashed",
    showQrCode: true,
    qrPosition: "left",
    qrSize: "sm",
    qrHasWhiteBg: true,
    showNetworkName: true,
    showNetworkSlogan: false,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: false,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: false,
    codeBoxStyle: "rounded-white",
    codeTextColor: "#0f172a",
    codeFontSize: "md",
    codeLetterSpacing: "wide",
    createdAt: "2026-08-22",
  },
  {
    id: "tpl-light-30",
    name: "قالب كروت 100 ريال الاقتصادي (A4 - 30 كارت موفر للحبر)",
    description: "خلفية بيضاء نقية موفرة للحبر تماماً، 30 كارت في الصفحة الواحدة لإنتاجية قصوى",
    categoryId: "cat-1",
    backgroundType: "minimal_light",
    themeColor: "#475569",
    accentColor: "#1e293b",
    cardsPerPage: 30,
    gridCols: 3,
    gridRows: 10,
    orientation: "portrait",
    paperSize: "A4",
    showCutLines: true,
    cutLineStyle: "dashed",
    showQrCode: true,
    qrPosition: "left",
    qrSize: "sm",
    qrHasWhiteBg: false,
    showNetworkName: true,
    showNetworkSlogan: false,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: false,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: false,
    codeBoxStyle: "clean-border",
    codeTextColor: "#0f172a",
    codeFontSize: "md",
    codeLetterSpacing: "wide",
    createdAt: "2026-08-22",
  },
  {
    id: "tpl-thermal-pos",
    name: "قالب إيصالات الطباعة الحرارية (Thermal POS 80mm)",
    description: "مخصص لطابعات الفواتير والكاشير الحرارية مقاس 80mm و 58mm مع باركود سريع",
    backgroundType: "minimal_light",
    themeColor: "#0f172a",
    accentColor: "#334155",
    cardsPerPage: 1,
    gridCols: 1,
    gridRows: 1,
    orientation: "portrait",
    paperSize: "Thermal80mm",
    showCutLines: false,
    showQrCode: true,
    qrPosition: "center",
    qrSize: "lg",
    qrHasWhiteBg: true,
    showNetworkName: true,
    showNetworkSlogan: true,
    showCategoryName: true,
    showPrice: true,
    showValidity: true,
    showQuota: true,
    showSpeed: true,
    showSerial: true,
    showSupportPhone: true,
    showInstructions: true,
    codeBoxStyle: "clean-border",
    codeTextColor: "#000000",
    codeFontSize: "xl",
    codeLetterSpacing: "widest",
    createdAt: "2026-08-23",
  }
];

export const initialExpenseCategories: ExpenseCategory[] = [
  {
    id: "exp-cat-1",
    name: "سعات وباقات الإنترنت الرئيسية (المزود)",
    description: "فواتير اشتراكات الإنترنت وخطوط الألياف والربط مع شركة الاتصالات / المزود الرئيسي",
    icon: "Wifi",
    colorTheme: "blue",
    isDefault: true,
  },
  {
    id: "exp-cat-2",
    name: "إيجارات الأبراج والمواقع",
    description: "إيجارات أسطح المنازل، الأبراج الرئيسية، ومواقع محطات البث",
    icon: "Radio",
    colorTheme: "purple",
    isDefault: true,
  },
  {
    id: "exp-cat-3",
    name: "الكهرباء والطاقة والمحروقات",
    description: "ديزل المولدات، فواتير الكهرباء، بطاريات ومنظومة الطاقة الشمسية",
    icon: "Zap",
    colorTheme: "amber",
    isDefault: true,
  },
  {
    id: "exp-cat-4",
    name: "الصيانة وقطع الغيار والتمديدات",
    description: "راوترات، كابلات شبكة، صحون ميكروتك، سويتشات، وصيانة ميدانية",
    icon: "Wrench",
    colorTheme: "emerald",
    isDefault: true,
  },
  {
    id: "exp-cat-5",
    name: "طباعة وتغليف وتوزيع الكروت",
    description: "مصاريف مطابع الكروت، الورق المقوى، التغليف الحراري، ونقل الدفعات",
    icon: "Printer",
    colorTheme: "rose",
    isDefault: true,
  },
  {
    id: "exp-cat-6",
    name: "رواتب ومكافآت الفنيين والموظفين",
    description: "رواتب مهندسي الشبكة، فنيي الصيانة، والمحصلين",
    icon: "Users",
    colorTheme: "indigo",
    isDefault: true,
  },
  {
    id: "exp-cat-7",
    name: "نثريات ومصاريف تشغيلية عامة",
    description: "مستلزمات مكتبية، اتصالات وضيافة، ومصروفات طارئة",
    icon: "Receipt",
    colorTheme: "slate",
    isDefault: true,
  },
];

export const initialExpenses: ExpenseRecord[] = [
  {
    id: "exp-1",
    voucherNumber: "EXP-2026-001",
    date: "2026-08-15",
    timestamp: "2026-08-15T11:00:00Z",
    categoryId: "exp-cat-1",
    categoryName: "سعات وباقات الإنترنت الرئيسية (المزود)",
    title: "سداد فاتورة باقة الإنترنت الرئيسية (سعة 200 ميجا فايبر)",
    amount: 65000,
    paymentMethod: "bank_transfer",
    paidTo: "المزود الرئيسي للاتصالات",
    referenceNumber: "TRX-889102",
    notes: "سداد اشتراك النصف الثاني من الشهر",
    createdByName: "المدير العام",
  },
  {
    id: "exp-2",
    voucherNumber: "EXP-2026-002",
    date: "2026-08-18",
    timestamp: "2026-08-18T16:30:00Z",
    categoryId: "exp-cat-3",
    categoryName: "الكهرباء والطاقة والمحروقات",
    title: "شراء محروقات ديزل لمولد برج القمة الرئيسي",
    amount: 18000,
    paymentMethod: "cash",
    paidTo: "محطة السلام للمحروقات",
    referenceNumber: "BILL-4412",
    notes: "تعبئة 60 لتر ديزل لتشغيل أوقات انقطاع الكهرباء",
    createdByName: "فني البرج",
  },
  {
    id: "exp-3",
    voucherNumber: "EXP-2026-003",
    date: "2026-08-20",
    timestamp: "2026-08-20T14:15:00Z",
    categoryId: "exp-cat-5",
    categoryName: "طباعة وتغليف وتوزيع الكروت",
    title: "طباعة دفعة 2000 كارت كوشيه مع كود QR وسيريال",
    amount: 14500,
    paymentMethod: "cash",
    paidTo: "مطابع الإبداع الحديثة",
    referenceNumber: "REC-9011",
    notes: "طباعة وتغليف كروت فئات 100، 200، 500 ريال",
    createdByName: "أمين المستودع",
  },
  {
    id: "exp-4",
    voucherNumber: "EXP-2026-004",
    date: "2026-08-22",
    timestamp: "2026-08-22T09:45:00Z",
    categoryId: "exp-cat-4",
    categoryName: "الصيانة وقطع الغيار والتمديدات",
    title: "شراء راوتر بورد مايكروتك RB750Gr3 وسويتش 8 منافذ",
    amount: 28000,
    paymentMethod: "bank_transfer",
    paidTo: "مؤسسة تقنية الشبكات",
    referenceNumber: "INV-5521",
    notes: "استبدال راوتر الموقع الفرعي في حي النخيل",
    createdByName: "مهندس الشبكة",
  },
  {
    id: "exp-5",
    voucherNumber: "EXP-2026-005",
    date: "2026-08-24",
    timestamp: "2026-08-24T18:00:00Z",
    categoryId: "exp-cat-6",
    categoryName: "رواتب ومكافآت الفنيين والموظفين",
    title: "سلفة من راتب فني الصيانة والميدان",
    amount: 15000,
    paymentMethod: "cash",
    paidTo: "م. خالد العديني",
    notes: "سلفة أسبوعية تحت حساب المستحقات",
    createdByName: "المدير المالي",
  },
];

export const initialInvoices: InvoiceRecord[] = [
  {
    id: "inv-101",
    invoiceNumber: "INV-2026-001",
    type: "sale",
    date: "2026-08-15",
    timestamp: "2026-08-15T10:30:00Z",
    posPointId: "pos-1",
    posPointName: "بقالة الأمانة والسلام",
    items: [
      {
        categoryId: "cat-1",
        categoryName: "كارت 100 ريال (1 ساعة / 500 ميجا)",
        quantity: 100,
        unitCostPrice: 25,
        unitWholesalePrice: 80,
        totalWholesalePrice: 8000,
        unitRetailPrice: 100,
        totalRetailPrice: 10000,
        profit: 5500,
        serialStart: "10001",
        serialEnd: "10100",
        notes: "حزمة 100 كارت",
      },
      {
        categoryId: "cat-2",
        categoryName: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
        quantity: 50,
        unitCostPrice: 50,
        unitWholesalePrice: 160,
        totalWholesalePrice: 8000,
        unitRetailPrice: 200,
        totalRetailPrice: 10000,
        profit: 5500,
        serialStart: "20001",
        serialEnd: "20050",
        notes: "حزمة 50 كارت",
      },
      {
        categoryId: "cat-3",
        categoryName: "كارت 500 ريال (يومي 24 ساعة / 3.5 جيجا)",
        quantity: 20,
        unitCostPrice: 130,
        unitWholesalePrice: 420,
        totalWholesalePrice: 8400,
        unitRetailPrice: 500,
        totalRetailPrice: 10000,
        profit: 5800,
        serialStart: "30001",
        serialEnd: "30020",
        notes: "كروت يومية",
      },
    ],
    totalQuantity: 170,
    totalWholesaleAmount: 24400,
    totalRetailAmount: 30000,
    totalCostAmount: 7600,
    totalProfit: 16800,
    paymentType: "credit",
    status: "completed",
    notes: "دفعة كروت شاملة ومتنوعة لبقالة الأمانة",
    receivedBy: "أبو أحمد الشامي",
    deliveredBy: "مندوب التوزيع",
  },
  {
    id: "inv-102",
    invoiceNumber: "INV-2026-002",
    type: "sale",
    date: "2026-08-18",
    timestamp: "2026-08-18T15:00:00Z",
    posPointId: "pos-2",
    posPointName: "كافيه ديوان القمة",
    items: [
      {
        categoryId: "cat-2",
        categoryName: "كارت 200 ريال (3 ساعات / 1.5 جيجا)",
        quantity: 120,
        unitCostPrice: 50,
        unitWholesalePrice: 160,
        totalWholesalePrice: 19200,
        unitRetailPrice: 200,
        totalRetailPrice: 24000,
        profit: 13200,
        serialStart: "20101",
        serialEnd: "20220",
      },
      {
        categoryId: "cat-3",
        categoryName: "كارت 500 ريال (يومي 24 ساعة / 3.5 جيجا)",
        quantity: 60,
        unitCostPrice: 130,
        unitWholesalePrice: 420,
        totalWholesalePrice: 25200,
        unitRetailPrice: 500,
        totalRetailPrice: 30000,
        profit: 17400,
        serialStart: "30051",
        serialEnd: "30110",
      },
    ],
    totalQuantity: 180,
    totalWholesaleAmount: 44400,
    totalRetailAmount: 54000,
    totalCostAmount: 13800,
    totalProfit: 30600,
    paymentType: "credit",
    status: "completed",
    notes: "دفعة نهاية الأسبوع للكافيه",
    receivedBy: "مروان الحداد",
    deliveredBy: "محصل الشبكة",
  },
  {
    id: "inv-103",
    invoiceNumber: "RET-2026-001",
    type: "return",
    date: "2026-08-22",
    timestamp: "2026-08-22T17:30:00Z",
    posPointId: "pos-1",
    posPointName: "بقالة الأمانة والسلام",
    items: [
      {
        categoryId: "cat-1",
        categoryName: "كارت 100 ريال (1 ساعة / 500 ميجا)",
        quantity: 10,
        unitWholesalePrice: 80,
        totalWholesalePrice: 800,
        unitRetailPrice: 100,
        totalRetailPrice: 1000,
        serialStart: "10091",
        serialEnd: "10100",
        notes: "استرجاع كروت تم استبدالها بفئة أخرى",
      },
    ],
    totalQuantity: 10,
    totalWholesaleAmount: 800,
    totalRetailAmount: 1000,
    paymentType: "credit",
    status: "completed",
    notes: "إرجاع 10 كروت وخصم قيمتها من رصيد الحساب المتبقي",
    reasonForReturn: "طلب استبدال بفئة أعلى",
    receivedBy: "أمين المستودع",
    deliveredBy: "أبو أحمد الشامي",
  },
  {
    id: "inv-104",
    invoiceNumber: "INV-2026-003",
    type: "sale",
    date: "2026-08-23",
    timestamp: "2026-08-23T11:20:00Z",
    posPointId: "pos-5",
    posPointName: "محل إكسبريس للاتصالات",
    items: [
      {
        categoryId: "cat-4",
        categoryName: "كارت 1000 ريال (3 أيام / 8 جيجا)",
        quantity: 30,
        unitCostPrice: 280,
        unitWholesalePrice: 850,
        totalWholesalePrice: 25500,
        unitRetailPrice: 1000,
        totalRetailPrice: 30000,
        profit: 17100,
        serialStart: "40001",
        serialEnd: "40030",
      },
      {
        categoryId: "cat-5",
        categoryName: "كارت 1500 ريال (أسبوعي 7 أيام / 15 جيجا)",
        quantity: 20,
        unitCostPrice: 420,
        unitWholesalePrice: 1250,
        totalWholesalePrice: 25000,
        unitRetailPrice: 1500,
        totalRetailPrice: 30000,
        profit: 16600,
        serialStart: "45001",
        serialEnd: "45020",
      },
      {
        categoryId: "cat-6",
        categoryName: "كارت 5000 ريال (شهري 30 يوم VIP / 60 جيجا)",
        quantity: 10,
        unitCostPrice: 1200,
        unitWholesalePrice: 4200,
        totalWholesalePrice: 42000,
        unitRetailPrice: 5000,
        totalRetailPrice: 50000,
        profit: 30000,
        serialStart: "50001",
        serialEnd: "50010",
      },
    ],
    totalQuantity: 60,
    totalWholesaleAmount: 92500,
    totalRetailAmount: 110000,
    totalCostAmount: 28800,
    totalProfit: 63700,
    paymentType: "credit",
    status: "completed",
    notes: "دفعة الكروت الأسبوعية والشهرية عالية السرعة",
    receivedBy: "طارق منصور",
    deliveredBy: "المحصل الرئيسي",
  },
];

export const initialUsers: AppUser[] = [
  {
    id: "user-admin",
    name: "م. ماجد الورد",
    username: "admin",
    password: "adminpassword",
    pinCode: "1234",
    email: "admin@alfadaa.net",
    phone: "770123456",
    role: "super_admin",
    customRoleName: "المدير العام والمالك",
    avatar: "👑",
    avatarBgColor: "bg-purple-600",
    status: "active",
    permissions: getRoleDefaultPermissions("super_admin"),
    notes: "الحساب الإداري الرئيسي - صلاحيات كاملة لكافة وظائف النظام والشبكة",
    createdAt: "2026-01-01",
    lastLogin: "2026-08-27 10:15",
  },
  {
    id: "user-accountant",
    name: "أ. عبد الله السعدي",
    username: "accountant",
    password: "accpassword",
    pinCode: "2233",
    email: "abdullah.acc@alfadaa.net",
    phone: "771987654",
    role: "accountant",
    customRoleName: "المحاسب المالي للشبكة",
    avatar: "💼",
    avatarBgColor: "bg-indigo-600",
    status: "active",
    permissions: getRoleDefaultPermissions("accountant"),
    notes: "إدارة الفواتير، المصروفات، سندات القبض، ومتابعة مديونيات الموزعين",
    createdAt: "2026-02-10",
    lastLogin: "2026-08-27 09:30",
  },
  {
    id: "user-sales1",
    name: "سالم بن علي",
    username: "sales1",
    password: "salespassword",
    pinCode: "5544",
    email: "salem.sales@alfadaa.net",
    phone: "773456789",
    role: "sales_agent",
    customRoleName: "مندوب توزيع ومبيعات الميدان",
    avatar: "🚚",
    avatarBgColor: "bg-cyan-600",
    status: "active",
    permissions: getRoleDefaultPermissions("sales_agent"),
    assignedPOSPointIds: ["pos-1", "pos-2", "pos-3"],
    maxDiscountPercent: 5,
    notes: "مسؤول تسليم كروت فئات 100، 200، 500 وتحصيل المبالغ من الموزعين",
    createdAt: "2026-03-01",
    lastLogin: "2026-08-26 18:45",
  },
  {
    id: "user-cashier",
    name: "فاطمة القدسي",
    username: "cashier",
    password: "cashierpassword",
    pinCode: "8899",
    email: "fatima.cashier@alfadaa.net",
    phone: "775678901",
    role: "cashier",
    customRoleName: "أمين صندوق الفرع الرئيسي",
    avatar: "🏪",
    avatarBgColor: "bg-emerald-600",
    status: "active",
    permissions: getRoleDefaultPermissions("cashier"),
    notes: "تسجيل سندات القبض النقدية وإصدار فواتير الاستلام الفورية",
    createdAt: "2026-04-15",
    lastLogin: "2026-08-27 08:00",
  },
  {
    id: "user-netadmin",
    name: "م. عمار الحمادي",
    username: "netadmin",
    password: "netadminpassword",
    pinCode: "4321",
    email: "ammar.net@alfadaa.net",
    phone: "777890123",
    role: "network_admin",
    customRoleName: "مهندس الشبكات والمايكروتك",
    avatar: "🌐",
    avatarBgColor: "bg-blue-600",
    status: "active",
    permissions: getRoleDefaultPermissions("network_admin"),
    notes: "إدارة راوترات المايكروتك، توليد كروت اليوزر مانجر، وضبط القوالب",
    createdAt: "2026-05-01",
    lastLogin: "2026-08-26 22:10",
  },
  {
    id: "user-auditor",
    name: "د. خالد الزبيري",
    username: "auditor",
    password: "auditorpassword",
    pinCode: "9900",
    email: "khaled.audit@alfadaa.net",
    phone: "772345678",
    role: "viewer",
    customRoleName: "المدقق والمراجع المالي",
    avatar: "👁️",
    avatarBgColor: "bg-amber-600",
    status: "active",
    permissions: getRoleDefaultPermissions("viewer"),
    notes: "حساب تدقيق خارجي - مراجعة السجلات وتصدير التقارير فقط",
    createdAt: "2026-06-20",
    lastLogin: "2026-08-25 14:00",
  },
  {
    id: "user-pos1",
    name: "أبو أحمد الشامي",
    username: "pos_amana",
    password: "pospassword1",
    pinCode: "1111",
    phone: "771234567",
    role: "pos_agent",
    posPointId: "pos-1",
    customRoleName: "صاحب بقالة الأمانة والسلام",
    avatar: "🏪",
    avatarBgColor: "bg-cyan-600",
    status: "active",
    permissions: getRoleDefaultPermissions("pos_agent"),
    notes: "حساب نقطة بيع - تقديم ومتابعة طلبات الكروت ومتابعة الحساب",
    createdAt: "2026-01-10",
    lastLogin: "2026-08-28 09:10",
  },
  {
    id: "user-pos2",
    name: "محمد اليعري",
    username: "pos_diwan",
    password: "pospassword2",
    pinCode: "2222",
    phone: "772345678",
    role: "pos_agent",
    posPointId: "pos-2",
    customRoleName: "مدير كافيه ديوان القمة",
    avatar: "☕",
    avatarBgColor: "bg-amber-600",
    status: "active",
    permissions: getRoleDefaultPermissions("pos_agent"),
    notes: "حساب نقطة بيع - طلبات الكروت ومتابعة كشف الحساب",
    createdAt: "2026-01-15",
    lastLogin: "2026-08-27 16:35",
  },
];

export const defaultNetworkSettings = initialNetworkSettings;
export const mockCategories = initialCategories;
export const mockPOSPoints = initialPOSPoints;
export const mockDispatches = initialDispatches;
export const mockSales = initialSales;
export const mockPayments = initialPayments;
export const mockGeneratedVouchers = initialGeneratedVouchers;
export const mockTemplates = initialTemplates;
export const mockExpenseCategories = initialExpenseCategories;
export const mockExpenses = initialExpenses;
export const mockInvoices = initialInvoices;
export const mockUsers = initialUsers;
export const mockCardOrders = initialCardOrders;


